openapi: 3.0.1
info:
  version: 2.0.3
  title: hotel_actialife
  description:
    "This is a Base API Project created by mi panita carzul"
servers:
  - url: http://localhost:8080/hotel.actialife-deploy/

#tags:
 # $ref: "./paths/public-tags.yaml"
paths:
  $ref: "./paths/public-paths.yaml"
components:
  parameters:
    $ref: "./parameters/public-parameters.yaml"
  schemas:
    $ref: "./schemas/public-schemas.yaml"
  responses:
    $ref: "./responses/public-responses.yaml"
  securitySchemes:
    $ref: "./security/schema/public-security-schemas.yaml"
security:
  $ref: "./security/api/public-security.yaml"