openapi: 3.0.1
info:
  version: 1.1.0
  title: swagger-base-api
  description:
    "This is a Base API Project created by [Procesos 4.0 - Ctag](http://ctag.com/). All doc that you need is [here](https://git.procesos.ctag.com/Paperless-API/docs)."
servers:
  - url: http://localhost:8080
  - url: https://you-backend-preprod-procesos.ctag
  - url: https://you-backend-prod-procesos.ctag
tags:
  $ref: './tags/public-tags.yaml'
paths:
  $ref: "./paths/public-paths.yaml"
components:
  parameters:
    $ref: "./parameters/public-parameters.yaml"
  schemas:
    $ref: "./schemas/public-schemas.yaml"
  responses:
    $ref: "./responses/public-responses.yaml"
