/*
 * hotel_actialife
 * This is a Base API Project created by mi panita carzul
 *
 * OpenAPI spec version: 2.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ctag.hotel.rest.model;

import java.util.Objects;
import java.util.Collections;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.v3.oas.annotations.media.Schema;
import javax.validation.constraints.*;

/**
 * HabitacionTipoCreateDto
 */
@javax.annotation.Generated(value = "com.ctag.codegen.languages.v3.java.jaxrs.JavaSeedstackJerseyServerCodegen", date = "2021-05-12T10:58:18.153+02:00[Europe/Paris]")public class HabitacionTipoCreateDto   {
  @JsonProperty("tipo_habitacion")
  protected String tipoHabitacion = null;

  @JsonProperty("precio")
  protected Float precio = null;

  @JsonProperty("descripcion")
  protected String descripcion = null;

  @JsonProperty("m2")
  protected Float m2 = null;

  @JsonProperty("numero_habitaciones")
  protected Integer numeroHabitaciones = null;


  public HabitacionTipoCreateDto(){
   //Empty Constructor
  }
  
  public HabitacionTipoCreateDto(HabitacionTipoCreateDto parentDto){
   
    this.tipoHabitacion = parentDto.tipoHabitacion;
    this.precio = parentDto.precio;
    this.descripcion = parentDto.descripcion;
    this.m2 = parentDto.m2;
    this.numeroHabitaciones = parentDto.numeroHabitaciones;
  }

 
  public HabitacionTipoCreateDto tipoHabitacion(String tipoHabitacion) {
    this.tipoHabitacion = tipoHabitacion;
    return this;
  }


 
  /**
   * Get tipoHabitacion
   * @return tipoHabitacion
   **/
  @JsonProperty("tipo_habitacion")
  @Schema(required = true, description = "")
  @NotNull
  public String getTipoHabitacion() {
    return tipoHabitacion;
  }
 

  public void setTipoHabitacion(String tipoHabitacion) {
    this.tipoHabitacion = tipoHabitacion;
  }
 

 
  public HabitacionTipoCreateDto precio(Float precio) {
    this.precio = precio;
    return this;
  }


 
  /**
   * Get precio
   * @return precio
   **/
  @JsonProperty("precio")
  @Schema(required = true, description = "")
  @NotNull
  public Float getPrecio() {
    return precio;
  }
 

  public void setPrecio(Float precio) {
    this.precio = precio;
  }
 

 
  public HabitacionTipoCreateDto descripcion(String descripcion) {
    this.descripcion = descripcion;
    return this;
  }


 
  /**
   * Get descripcion
   * @return descripcion
   **/
  @JsonProperty("descripcion")
  @Schema(description = "")
  public String getDescripcion() {
    return descripcion;
  }
 

  public void setDescripcion(String descripcion) {
    this.descripcion = descripcion;
  }
 

 
  public HabitacionTipoCreateDto m2(Float m2) {
    this.m2 = m2;
    return this;
  }


 
  /**
   * Get m2
   * @return m2
   **/
  @JsonProperty("m2")
  @Schema(required = true, description = "")
  @NotNull
  public Float getM2() {
    return m2;
  }
 

  public void setM2(Float m2) {
    this.m2 = m2;
  }
 

 
  public HabitacionTipoCreateDto numeroHabitaciones(Integer numeroHabitaciones) {
    this.numeroHabitaciones = numeroHabitaciones;
    return this;
  }


 
  /**
   * Get numeroHabitaciones
   * @return numeroHabitaciones
   **/
  @JsonProperty("numero_habitaciones")
  @Schema(required = true, description = "")
  @NotNull
  public Integer getNumeroHabitaciones() {
    return numeroHabitaciones;
  }
 

  public void setNumeroHabitaciones(Integer numeroHabitaciones) {
    this.numeroHabitaciones = numeroHabitaciones;
  }
 


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HabitacionTipoCreateDto HabitacionTipoCreate = (HabitacionTipoCreateDto) o;
    return Objects.equals(this.tipoHabitacion, HabitacionTipoCreate.tipoHabitacion) &&
        Objects.equals(this.precio, HabitacionTipoCreate.precio) &&
        Objects.equals(this.descripcion, HabitacionTipoCreate.descripcion) &&
        Objects.equals(this.m2, HabitacionTipoCreate.m2) &&
        Objects.equals(this.numeroHabitaciones, HabitacionTipoCreate.numeroHabitaciones);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tipoHabitacion, precio, descripcion, m2, numeroHabitaciones);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HabitacionTipoCreateDto {\n");
    
    sb.append("    tipoHabitacion: ").append(toIndentedString(tipoHabitacion)).append("\n");
    sb.append("    precio: ").append(toIndentedString(precio)).append("\n");
    sb.append("    descripcion: ").append(toIndentedString(descripcion)).append("\n");
    sb.append("    m2: ").append(toIndentedString(m2)).append("\n");
    sb.append("    numeroHabitaciones: ").append(toIndentedString(numeroHabitaciones)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
