/*
 * hotel_actialife
 * This is a Base API Project created by mi panita carzul
 *
 * OpenAPI spec version: 2.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ctag.hotel.rest.model;

import java.util.Objects;
import java.util.Collections;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.v3.oas.annotations.media.Schema;
import javax.validation.constraints.*;

/**
 * Step Create DTO
 */
@Schema(description = "Step Create DTO")
@javax.annotation.Generated(value = "com.ctag.codegen.languages.v3.java.jaxrs.JavaSeedstackJerseyServerCodegen", date = "2021-05-12T10:58:18.153+02:00[Europe/Paris]")public class UsercreateDto   {
  @JsonProperty("name")
  protected String name = null;

  @JsonProperty("surname")
  protected String surname = null;

  @JsonProperty("email")
  protected String email = null;

  @JsonProperty("telf")
  protected String telf = null;

  @JsonProperty("address")
  protected String address = null;

  @JsonProperty("password")
  protected String password = null;

  @JsonProperty("roleId")
  protected Integer roleId = null;


  public UsercreateDto(){
   //Empty Constructor
  }
  
  public UsercreateDto(UsercreateDto parentDto){
   
    this.name = parentDto.name;
    this.surname = parentDto.surname;
    this.email = parentDto.email;
    this.telf = parentDto.telf;
    this.address = parentDto.address;
    this.password = parentDto.password;
    this.roleId = parentDto.roleId;
  }

 
  public UsercreateDto name(String name) {
    this.name = name;
    return this;
  }


 
  /**
   * Get name
   * @return name
   **/
  @JsonProperty("name")
  @Schema(required = true, description = "")
  @NotNull
  public String getName() {
    return name;
  }
 

  public void setName(String name) {
    this.name = name;
  }
 

 
  public UsercreateDto surname(String surname) {
    this.surname = surname;
    return this;
  }


 
  /**
   * Get surname
   * @return surname
   **/
  @JsonProperty("surname")
  @Schema(required = true, description = "")
  @NotNull
  public String getSurname() {
    return surname;
  }
 

  public void setSurname(String surname) {
    this.surname = surname;
  }
 

 
  public UsercreateDto email(String email) {
    this.email = email;
    return this;
  }


 
  /**
   * Get email
   * @return email
   **/
  @JsonProperty("email")
  @Schema(required = true, description = "")
  @NotNull
  public String getEmail() {
    return email;
  }
 

  public void setEmail(String email) {
    this.email = email;
  }
 

 
  public UsercreateDto telf(String telf) {
    this.telf = telf;
    return this;
  }


 
  /**
   * Get telf
   * @return telf
   **/
  @JsonProperty("telf")
  @Schema(required = true, description = "")
  @NotNull
  public String getTelf() {
    return telf;
  }
 

  public void setTelf(String telf) {
    this.telf = telf;
  }
 

 
  public UsercreateDto address(String address) {
    this.address = address;
    return this;
  }


 
  /**
   * Get address
   * @return address
   **/
  @JsonProperty("address")
  @Schema(required = true, description = "")
  @NotNull
  public String getAddress() {
    return address;
  }
 

  public void setAddress(String address) {
    this.address = address;
  }
 

 
  public UsercreateDto password(String password) {
    this.password = password;
    return this;
  }


 
  /**
   * Get password
   * @return password
   **/
  @JsonProperty("password")
  @Schema(required = true, description = "")
  @NotNull
  public String getPassword() {
    return password;
  }
 

  public void setPassword(String password) {
    this.password = password;
  }
 

 
  public UsercreateDto roleId(Integer roleId) {
    this.roleId = roleId;
    return this;
  }


 
  /**
   * Get roleId
   * @return roleId
   **/
  @JsonProperty("roleId")
  @Schema(required = true, description = "")
  @NotNull
  public Integer getRoleId() {
    return roleId;
  }
 

  public void setRoleId(Integer roleId) {
    this.roleId = roleId;
  }
 


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UsercreateDto Usercreate = (UsercreateDto) o;
    return Objects.equals(this.name, Usercreate.name) &&
        Objects.equals(this.surname, Usercreate.surname) &&
        Objects.equals(this.email, Usercreate.email) &&
        Objects.equals(this.telf, Usercreate.telf) &&
        Objects.equals(this.address, Usercreate.address) &&
        Objects.equals(this.password, Usercreate.password) &&
        Objects.equals(this.roleId, Usercreate.roleId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, surname, email, telf, address, password, roleId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsercreateDto {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    surname: ").append(toIndentedString(surname)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    telf: ").append(toIndentedString(telf)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    roleId: ").append(toIndentedString(roleId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
