/*
 * hotel_actialife
 * This is a Base API Project created by mi panita carzul
 *
 * OpenAPI spec version: 2.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package actialife;

import java.util.Objects;
import java.util.Collections;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.v3.oas.annotations.media.Schema;
import javax.validation.constraints.*;

/**
 * LogsCreateDto
 */
@javax.annotation.Generated(value = "com.ctag.codegen.languages.v3.java.jaxrs.JavaSeedstackJerseyServerCodegen", date = "2021-04-30T12:30:57.699+02:00[Europe/Paris]")public class LogsCreateDto   {
  @JsonProperty("idUser")
  protected Integer idUser = null;

  @JsonProperty("log")
  protected String log = null;

  @JsonProperty("time")
  protected String time = null;


  public LogsCreateDto(){
   //Empty Constructor
  }
  
  public LogsCreateDto(LogsCreateDto parentDto){
   
    this.idUser = parentDto.idUser;
    this.log = parentDto.log;
    this.time = parentDto.time;
  }

 
  public LogsCreateDto idUser(Integer idUser) {
    this.idUser = idUser;
    return this;
  }


 
  /**
   * Get idUser
   * @return idUser
   **/
  @JsonProperty("idUser")
  @Schema(required = true, description = "")
  @NotNull
  public Integer getIdUser() {
    return idUser;
  }
 

  public void setIdUser(Integer idUser) {
    this.idUser = idUser;
  }
 

 
  public LogsCreateDto log(String log) {
    this.log = log;
    return this;
  }


 
  /**
   * Get log
   * @return log
   **/
  @JsonProperty("log")
  @Schema(required = true, description = "")
  @NotNull
  public String getLog() {
    return log;
  }
 

  public void setLog(String log) {
    this.log = log;
  }
 

 
  public LogsCreateDto time(String time) {
    this.time = time;
    return this;
  }


 
  /**
   * Get time
   * @return time
   **/
  @JsonProperty("time")
  @Schema(required = true, description = "")
  @NotNull
  public String getTime() {
    return time;
  }
 

  public void setTime(String time) {
    this.time = time;
  }
 


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LogsCreateDto LogsCreate = (LogsCreateDto) o;
    return Objects.equals(this.idUser, LogsCreate.idUser) &&
        Objects.equals(this.log, LogsCreate.log) &&
        Objects.equals(this.time, LogsCreate.time);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idUser, log, time);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LogsCreateDto {\n");
    
    sb.append("    idUser: ").append(toIndentedString(idUser)).append("\n");
    sb.append("    log: ").append(toIndentedString(log)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
