/*
 * hotel_actialife
 * This is a Base API Project created by mi panita carzul
 *
 * OpenAPI spec version: 2.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package actialife;

import java.util.Objects;
import java.util.Collections;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;

/**
 * Base DTO, reserva Extension with role
 */
@Schema(description = "Base DTO, reserva Extension with role")
@javax.annotation.Generated(value = "com.ctag.codegen.languages.v3.java.jaxrs.JavaSeedstackJerseyServerCodegen", date = "2021-05-10T14:13:55.611+02:00[Europe/Paris]")public class ReservasExtendedUserDto extends ReservasDto  {
  @JsonProperty("user")
  protected List<UserDto> user = null;


  public ReservasExtendedUserDto(){
   //Empty Constructor
  }
  
  public ReservasExtendedUserDto(ReservasExtendedUserDto parentDto){
   super(parentDto);
    this.user = parentDto.user;
  }

 
  public ReservasExtendedUserDto user(List<UserDto> user) {
    if (this.user == null) {
        this.user = new ArrayList<>();
    }
    this.user.addAll(user);
    return this;
  }


  public ReservasExtendedUserDto addUserItem(UserDto userItem) {
    if (this.user == null) {
      this.user = new ArrayList<>();
    }
    this.user.add(userItem);
    return this;
  }

 
  /**
   * Get user
   * @return user
   **/
  @JsonProperty("user")
  @Schema(description = "")
  public List<UserDto> getUser() {
    if (this.user == null) {
    return Collections.emptyList();
    }
    return user;
  }
 

  public void setUser(List<UserDto> user) {
    if (this.user == null) {
        this.user = new ArrayList<>();
    }
    this.user.addAll(user);
  }
 


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReservasExtendedUserDto ReservasExtendedUser = (ReservasExtendedUserDto) o;
    return Objects.equals(this.user, ReservasExtendedUser.user) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(user);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReservasExtendedUserDto {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
