/*
 * hotel_actialife
 * This is a Base API Project created by mi panita carzul
 *
 * OpenAPI spec version: 2.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package actialife;

import java.util.Objects;
import java.util.Collections;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.v3.oas.annotations.media.Schema;
import javax.validation.constraints.*;

/**
 * RolecreateDto
 */
@javax.annotation.Generated(value = "com.ctag.codegen.languages.v3.java.jaxrs.JavaSeedstackJerseyServerCodegen", date = "2021-04-26T12:23:21.276+02:00[Europe/Paris]")public class RolecreateDto   {
  @JsonProperty("nombreRol")
  protected String nombreRol = null;


  public RolecreateDto(){
   //Empty Constructor
  }
  
  public RolecreateDto(RolecreateDto parentDto){
   
    this.nombreRol = parentDto.nombreRol;
  }

 
  public RolecreateDto nombreRol(String nombreRol) {
    this.nombreRol = nombreRol;
    return this;
  }


 
  /**
   * Get nombreRol
   * @return nombreRol
   **/
  @JsonProperty("nombreRol")
  @Schema(required = true, description = "")
  @NotNull
  public String getNombreRol() {
    return nombreRol;
  }
 

  public void setNombreRol(String nombreRol) {
    this.nombreRol = nombreRol;
  }
 


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RolecreateDto Rolecreate = (RolecreateDto) o;
    return Objects.equals(this.nombreRol, Rolecreate.nombreRol);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nombreRol);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RolecreateDto {\n");
    
    sb.append("    nombreRol: ").append(toIndentedString(nombreRol)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
