/*
 * hotel_actialife
 * This is a Base API Project created by mi panita carzul
 *
 * OpenAPI spec version: 2.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package actialife;

import java.util.Objects;
import java.util.Collections;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.v3.oas.annotations.media.Schema;
import javax.validation.constraints.*;

/**
 * user of mf bussiness money money
 */
@Schema(description = "user of mf bussiness money money")
@javax.annotation.Generated(value = "com.ctag.codegen.languages.v3.java.jaxrs.JavaSeedstackJerseyServerCodegen", date = "2021-04-30T12:30:57.699+02:00[Europe/Paris]")public class UserDto extends UsercreateDto  {
  @JsonProperty("userId")
  protected Integer userId = null;


  public UserDto(){
   //Empty Constructor
  }
  
  public UserDto(UserDto parentDto){
   super(parentDto);
    this.userId = parentDto.userId;
  }

 
  public UserDto userId(Integer userId) {
    this.userId = userId;
    return this;
  }


 
  /**
   * Get userId
   * @return userId
   **/
  @JsonProperty("userId")
  @Schema(required = true, description = "")
  @NotNull
  public Integer getUserId() {
    return userId;
  }
 

  public void setUserId(Integer userId) {
    this.userId = userId;
  }
 


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserDto User = (UserDto) o;
    return Objects.equals(this.userId, User.userId) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserDto {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
