/*
 * hotel_actialife
 * This is a Base API Project created by mi panita carzul
 *
 * OpenAPI spec version: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package actialife;

import java.util.Objects;
import java.util.Collections;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;

/**
 * Base DTO, user Extension with role
 */
@Schema(description = "Base DTO, user Extension with role")
@javax.annotation.Generated(value = "com.ctag.codegen.languages.v3.java.jaxrs.JavaSeedstackJerseyServerCodegen", date = "2021-04-23T14:13:04.663+02:00[Europe/Paris]")public class UsersExtendedDto extends UserDto  {
  @JsonProperty("role")
  protected List<RoleDto> role = new ArrayList<>();


  public UsersExtendedDto(){
   //Empty Constructor
  }
  
  public UsersExtendedDto(UsersExtendedDto parentDto){
   super(parentDto);
    this.role = parentDto.role;
  }

 
  public UsersExtendedDto role(List<RoleDto> role) {
    this.role.addAll(role);
    return this;
  }


  public UsersExtendedDto addRoleItem(RoleDto roleItem) {
    this.role.add(roleItem);
    return this;
  }

 
  /**
   * Get role
   * @return role
   **/
  @JsonProperty("role")
  @Schema(required = true, description = "")
  @NotNull
  public List<RoleDto> getRole() {
    if (this.role == null) {
    return Collections.emptyList();
    }
    return role;
  }
 

  public void setRole(List<RoleDto> role) {
    this.role.addAll(role);
  }
 


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UsersExtendedDto UsersExtended = (UsersExtendedDto) o;
    return Objects.equals(this.role, UsersExtended.role) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(role);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsersExtendedDto {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
